### ISSUE TITLE
Modal Windows (Alerts)

### ISSUE THREAD

**Issue by ghost** [saphero/sphero-hack#28]
Create custom modal window to be used for app alerts. Or maybe use a plugin if lazy.

**Comment by xxnatc** [comment]
I was looking into Sweet Alert: http://t4t5.github.io/sweetalert/

**Comment by xxnatc** [comment]
Another one, looks almost the same: http://limonte.github.io/sweetalert2/

**Comment by ghost** [comment]
I like them! I'll see if I can integrate them into the client side.
