### ISSUE TITLE
Create Client Side

### ISSUE THREAD

**Issue by jessethach** [saphero/sphero-hack#4]
Client side dashboard with preset controls of basic color and commands

**Comment by ghost** [comment]
Currently looking into this...will have info to share come Sunday. :)

**Comment by xxnatc** [comment]
**Just a list to keep track:**
- [x] index aka connect page
- [x] start motion control page
- [x] color picker
- [x] finish about page
- [x] remove settings page (for now)
- [x] setting up modal
- [x] nav click actions
- [x] lastly: hook up controls and data streaming
